### ISSUE TITLE
Dylib of LibSparkAppList not detected

### ISSUE THREAD

**Issue by dhellwich** [opa334/Choicy#11]
Source of LibSparkApplist:
https://www.sparkdev.me/package/com.spark.libsparkapplist

LibSparkAppList is an AppList alternative.
The plist of the dylib (SparkAppListSB.dylib) indicates that it should inject into: com.apple.springboard

Choicy does not show this tweak in "Global Tweak Configuration" and also not in "SpringBoard" process configuration.

This causes issues when SpringBoard is set to use a whitelist custom tweak configuration, because SparkAppListSB.dylib is not being injected into SpringBoard, causing issues with tweaks which depend on SparkAppListSB.dylib.

Just a suggestion, but maybe this issue/bug is caused by your hardcoded AppList filtering(?).

**Comment by opa334** [comment]
🤦‍♂️ yeah, it probably wasn't a good idea to check if the filename contains "AppList", will be fixed soon
