### ISSUE TITLE
Powercuff dylib not detected in SpringBoard

### ISSUE THREAD

**Issue by dhellwich** [opa334/Choicy#13]
Powercuff tweak (by Ryan Petrich) is not detected as a tweak which injects into SpringBoard. The plist of this tweak injects into SpringBoard executable (instead of com.apple.springboard bundle).
Because of this Choicy does not detect this tweak, which is causing issues with the SpringBoard whitelisting functionality of Choicy (tweak doesn't get injected).

Could you please add SpringBoard executable to Choicy's SpringBoard filter?

**Comment by opa334** [comment]
This should have been fixed already in like 1.2.1, will take another look soon.

**Comment by dhellwich** [comment]
Thanks @opa334 ! 

At this moment I'm not using Powercuff anymore, but it seemed like a bug (which could also happen with other tweaks), that's why I reported it. Anyway, happy bug hunting! :)
