### ISSUE TITLE
Choicy not working libhooker and Odysseyra1n

### ISSUE THREAD

**Issue by EzrahFTW** [opa334/Choicy#14]
not working :(

**Comment by opa334** [comment]
works fine

**Comment by EzrahFTW** [comment]
not working I’ve been banned from Snapchat using Odysseyra1n, with checkra1n I never be banned 

Envoyé de mon iPhone

**Comment by opa334** [comment]
Yes, Choicy however still prevents tweaks from injecting as intended. So it works fine. Use Picahide and put it on the whitelist for Snapchat to prevent bans.

**Comment by EzrahFTW** [comment]
Picahide just crashing my iPhone. I really think is Choicy compatibility with Libhooker because with substrate I never have a problem 

Envoyé de mon iPhone
