### ISSUE TITLE
Single clicking home button doesn't work

### ISSUE THREAD

**Issue by numselli** [opa334/Choicy#16]
I was on version 1.3 when I single clicked the home button it would do nothing, double clicking would bring up the app switcher. Clicking and holding would activate Siri but the overlay would not show.

iOS 13.5.1
Choice￼ 1.3
iPhone 6s

**Comment by opa334** [comment]
can't reproduce, also I fail to see how Choicy would even be able to cause this as it does not hook anything related to the home button
