### ISSUE TITLE
Global Whitelist has issues.

### ISSUE THREAD

**Issue by GTO683** [opa334/Choicy#21]
When I select tweaks to whitelist and respring, for some reason it disables all tweaks except for the ones I whitelisted.

**Comment by opa334** [comment]
there is no global whitelist, only a global blacklist, you may be misinterpreting the "overwrite" options (and in that case, you should read their description again)

**Comment by GTO683** [comment]
Ok. What you wrote [here](https://imgur.com/a/mfVNpMc) doesn't do what it says.
