### ISSUE TITLE
Unreliability on iOS 15+ when an app is launched in background by the system

### ISSUE THREAD

**Issue by miosx** [opa334/Choicy#31]
Launch without tweaks sometimes won't work.
Especially when you run an app for the first time After respring.
But then run it again and it succeeds

Fugu15Max beta8

**Comment by siberianspot** [comment]
> [test app] https://apps.apple.com/us/app/id794862904
> if Launch with tweaks, it says detected jailbreak.
> if Launch without tweaks succeeds, it says nothing.
> I do Launch without tweaks everytime, but sometimes it says detected jailbreak.
> so, maybe there is a bug in Choicy or Fugu15MAX.

This happens due the changes was made in 1.4.9 version. It seems that 1.4.9-2 preserves the same mechanism, but you could give it a try. When i noticed that Choicy started skipping some injections, i checked the code and downgraded to 1.4.8. And so far there hasn’t a time to make a PR :(

**Comment by opa334** [comment]
This has nothing to do with 1.4.9.

The problem is that in iOS 15 there is a mechanism that loads apps in the background, these launches are not going through SpringBoard though and that's why the Choicy hook does not catch them and cannot disable tweaks. A new runningboardd hook is likely needed for that, I have tried this in the past but couldn't find the flow that it uses for background launching apps and it's really hard to observe as it happens randomly, I do plan on addressing it in a future update however.

**Comment by miosx** [comment]
@opa334 Thanks for the explanation

**Comment by siberianspot** [comment]
> This has nothing to do with Choicy 1.4.9.
> 
> If you look at the diff, all changes of Choicy 1.4.9 were in the preference bundle, none of the main logic has changed.
> 
> The problem is that in iOS 15 and above there is a mechanism that loads apps in the background, these launches are not going through SpringBoard though and that's why the Choicy hook does not catch them and cannot disable tweaks. A new runningboardd hook is likely needed for that, I have tried this in the past but couldn't find the flow that it uses for background launching apps and it's really hard to observe as it happens randomly, I do plan on addressing it in a future update however. So when an app is launched in the background, tweaks will load even if you disabled it in Choicy settings.

Thanks for info! But 1.4.8 recognizes many more tweaks (so I thought 1.4.9 just ignores them doing this new app/extension checking. So far I have not noticed any unauthorized injection, but I have not looked for it intentionally. It’s good to know now

**Comment by miosx** [comment]
1.4.10 fix this issue.

**Comment by opa334** [comment]
> > This has nothing to do with Choicy 1.4.9.
> > If you look at the diff, all changes of Choicy 1.4.9 were in the preference bundle, none of the main logic has changed.
> > The problem is that in iOS 15 and above there is a mechanism that loads apps in the background, these launches are not going through SpringBoard though and that's why the Choicy hook does not catch them and cannot disable tweaks. A new runningboardd hook is likely needed for that, I have tried this in the past but couldn't find the flow that it uses for background launching apps and it's really hard to observe as it happens randomly, I do plan on addressing it in a future update however. So when an app is launched in the background, tweaks will load even if you disabled it in Choicy settings.
> 
> Thanks for info! But 1.4.8 recognizes many more tweaks (so I thought 1.4.9 just ignores them doing this new app/extension checking). So far I have not noticed any unauthorized injection, but I have not looked for it intentionally though. It’s good to know now. I will try to catch any strange app launches

1.4.8 does not detect more tweaks than 1.4.9. That logic also has not changed.
