### ISSUE TITLE
Merge deb

### ISSUE THREAD

**Issue by CoderFeiSu** [opa334/Choicy#34]
Please tell me how you merged rootfull and rootless into one deb. To execute release_build.sh, you are using Xcode11 and Xcode16, then Xcode11 compiles rootfull and Xcode16 compiles rootless.

**Comment by opa334** [comment]
They are not merged into the same deb. Compiling the rootful build with Xcode 11 is needed to maintain iOS 12 - 13 arm64e support.

**Comment by CoderFeiSu** [comment]
Thank you for your reply, but I found that the Choicy you uploaded to thebigboss supports both rootfull and rootless. Are they the same deb?

**Comment by opa334** [comment]
no

**Comment by CoderFeiSu** [comment]
You must use Xcode 14 (iPhoneOS 16.0) to compile rootless. Can I use Xcode13 (iPhoneOS 15.0)? Or I ask this, what are the requirements for macOS version and Xcode version to compile rootless. When I use macOS 12.6.3 and Xcode14.2 to compile rootless it is normal. When I use macOS 11.6.6 and Xcode13.2 to compile rootless it is abnormal. PreferenceLoader shows a loading error.

**Comment by opa334** [comment]
You don't need anything special to compile rootless.
