### ISSUE TITLE
Add ability to block livefileproviderd from loading Substrate tweaks

### ISSUE THREAD

**Issue by Siggi88** [opa334/Choicy#7]
/System/Library/PrivateFrameworks/UserFS.framework/livefileproviderd is the daemon that is launched when you mount an SMB drive in the Files app, but some tweak I have is breaking it.  Can’t find livefileproviderd in Choicy settings.

**Comment by opa334** [comment]
It appears for me after pressing "Show all daemons" at the bottom of the Choicy daemon settings, please try it out

**Comment by Siggi88** [comment]
It does not show up for me
![IMG_7162E62B6CE1-1](https://user-images.githubusercontent.com/7286178/72414487-4e416580-37ad-11ea-9490-b80eb0f2c502.jpeg)

**Comment by opa334** [comment]
If it does not show up, that probably means that no tweak is injecting into it, those processes are automatically hidden

**Comment by Siggi88** [comment]
I usually rename MobileSubstrate.dylib to MobileSubstrate.dylib.bak before mounting SMB drives and then renaming it back after it's been mounted to prevent it from injecting livefileproviderd, would that be why?  I also just tried leaving MobileSubstrate.dylib as is and killing livefileproviderd so that it would restart itself with MobileSubstrate and it still doesn't show up?

**Comment by opa334** [comment]
Try installing Cr4shed, it should show up for sure then. Disable tweak injection into it and check if your issue is fixed.

**Comment by Siggi88** [comment]
It worked, thanks!
